endpoints:
  enabled: true
  metrics:
    enabled: true

server:
   tomcat:
      max-threads: 20
cs:
   poke:
      server: http://poke-service.us-west-2.test.expedia.com:80/api/poke
      enabled: false
