monitoringAgent:
  statsd:
    hostname: "statsd-lab.test.expedia.com"
cs:
  poke:
    enabled: true
    server: http://poke-service.us-west-2.test.expedia.com:80/api/poke

server:
  port: 8080
# TODO remove addtional.port once all clients moved to HTTPS
  additional:
    port: 8181
  ssl:
    enabled: false

