spring:
  boot:
    admin:
      client:
        enabled: false

server:
  port: 8080
  ssl:
    enabled: false

logging:
  level:
    expedia.content: DEBUG
    org.springframework: INFO

cs:
  metrics:
    publisher:
      enabled: false
    statsd:
      hostname: localhost
  poke:
    enabled: false
